import type { CapabilityTag } from "../interfaces/intent.js";

export const DEFAULT_CAPABILITY_MAP: Record<CapabilityTag, string> = {
  "code-review": "senior-engineer",
  "debug": "debugger",
  "refactor": "senior-engineer",
  "architecture-analysis": "solution-architect",
  "implementation": "coder",
  "test-strategy": "test-strategist",
  "test-scenarios": "scenario-generator",
  "test-execution": "scenario-executor",
  "orchestrate": "orchestrator",
  "phase-routing": "orchestrator",
  "progress-report": "delivery-manager",
  "memory-store": "default",
  "memory-recall": "default",
  "context-assembly": "default",
  "security-scan": "security-engineer",
  "compliance-check": "compliance-officer",
  "cicd-pipeline": "devops-engineer",
  "requirements": "requirements-analyst",
  "brainstorm": "facilitator",
  "ux-review": "ux-designer",
  "acceptance-criteria": "requirements-analyst",
  "data-analysis": "data-analyst",
  "pipeline-design": "data-engineer",
  "ml-guidance": "ml-engineer",
  "code-patch": "coder",
  "cross-language-propagation": "coder",
  "general": "default",
};
